server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # O "Encaminhador" (Proxy)
    # Tudo que o navegador pedir para /api, o Nginx joga para o container 'api'
    location /api/ {
        proxy_pass http://api:3000/; 
        proxy_set_header Host $host;
    }
}