services:
  db:
    image: postgres:15-alpine
    container_name: joao_db
    environment:
      POSTGRES_USER: fatec_user
      POSTGRES_PASSWORD: fatec_password
      POSTGRES_DB: todolist
    volumes:
      - joao_data:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: joao_api
    restart: always
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "3001:3000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/tarefas"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s  
    
  web:
    build: ./frontend
    container_name: joao_web
    ports:
      - "8001:80"
    depends_on:
      api:
        condition: service_healthy

volumes:
  joao_data: