name: pipeline

on:
  push:
    branches:
      - main
      
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build com Docker Compose
        run: docker compose build

      - name: Push com Docker Compose
        run: docker compose push

  deploy:
    needs: build # Ou o nome do seu job de build/test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH (Appleboy)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Entra na home do usuário
            cd ~
            # Se o projeto não existe, clona. Se existe, pull.
            if [ ! -d "joao-app" ]; then
              git clone https://github.com/${{ github.repository }} joao-app
            fi
            cd joao-app
            git pull origin main
            docker compose pull
            # ALTERAÇÃO AQUI: Adicionado --build e --force-recreate
            docker compose up -d --build --force-recreate